# User Setting
gmail:
  username: whdqhd5402
github:
  username: whdqhd5402
gitlab:
  username: 
google-analytics: 
  ua:
disqus:
  username: whdqhd5402

username: whdqhd5402
# Site Path Setting
host:
port:
url: 
baseurl: 

# Search
search: true

# Site Info Setting
title: 
intro: 

# Permalink Setting
permalink: pretty

# Paginator Setting
paginator:
  size: 5

# Collection Setting
collections:
  docs:
    output: true
    permalink: /:collection/:path
  journals:
    output: true
    permalink: /:collection/:path
  tags:
    output: true
    permalink: /:collection/:path
  categories:
    output: true
    permalink: /:collection/:path
  # jekyll:
  #   output: true
  # gitlab:
  #   output: true

# Default Setting
defaults:
  # -
  #   scope:
  #     path: _jekyll
  #     type: jekyll # candidate only collection name
  #   values:
  #     permalink: docs/jekyll/:title
  # -
  #   scope:
  #     path: _gitlab
  #     type: gitlab
  #   values:
  #     permalink: docs/gitlab/:title

# Markdown Setting
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
    # block:
    #   line_numbers: true
  # highlighter: rouge
  # input: GFM

# Build Setting
exclude:
  - Gemfile
  - Gemfile.lock